trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(System.DefaultWorkingDirectory)/*'
    azureSubscription: 'd7eaf6ab-d1ec-47d3-a1d5-2aa5963f4132'
    Destination: 'AzureBlob'
    storage: 'waihfun'
    ContainerName: '$web'